# Generated by Django 5.1.6 on 2025-02-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc1', models.FileField(upload_to='validated/')),
                ('doc2', models.FileField(upload_to='validated/')),
                ('updated_doc', models.FileField(upload_to='validated/')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='uploaded_file',
        ),
    ]
